### ISSUE TITLE
Stopped working - no longer populates the screen

### ISSUE THREAD

**Issue by RGN01** [daniel-windsor/MMM-eswordoftheday#2]
![SpanishWordOfTheDay](https://user-images.githubusercontent.com/12368529/123510824-7e18bc00-d675-11eb-9cb2-8fde87c53df0.png)
![SpanishWordOfTheDay1](https://user-images.githubusercontent.com/12368529/123510828-81ac4300-d675-11eb-9104-0c961204823e.png)

After working perfectly for a few weeks (thank you for a great module, @daniel-windsor ) MMM-eswordoftheday has suddenly stopped working. To my VERY amateur eye it appears to not be getting the correct response from the website.

If I use Chromium on the Pi, it renders the https://www.spanishdict.com/wordoftheday page perfectly.

As you can see on the images, I have tried to debug but have so little prior understanding of MM and css, I'm fumbling in the dark! ;-) so any help would be VERY much appreciated!

Thanks.

**Comment by daniel-windsor** [comment]
Thanks for letting me know!  I would guess the web scraper isn't working because they changed something about their site. I'll check it out.

**Comment by RGN01** [comment]
Thank you so much!

**Comment by RGN01** [comment]
Hi Daniel. Is there anything I can do to help? I am by no means a programmer but can 'dabble' and can test if that helps?

**Comment by thefonz88** [comment]
I was really looking forward to use this module for my wife's mirror but I'm having the same issue with no data.

**Comment by AndreRH** [comment]
Same here

**Comment by smrz10** [comment]
I did this changes (node_helper.js):

`//const container = $(".entry--1qTEOKKt")[0];`
` container = $("._1qTEOKKt")[0];`

and it works
`

**Comment by RGN01** [comment]
THANK YOU!

I edited the node_helper.js file inline, then rebooted and it worked! I did have to make a slight change to your text above and ended up with (I did try formatting as code but couldn't force the new line on here):
        //const container = $(".entry--1qTEOKKt")[0];
        const container = $("._1qTEOKKt")[0];


Thank you so much - my wife is learning Spanish and this will make her day!

**Comment by AndreRH** [comment]
> I did this changes (node_helper.js):
> 
> `//const container = $(".entry--1qTEOKKt")[0];`
> ` container = $("._1qTEOKKt")[0];`
> 
> and it works
> `

You should do a pull request

**Comment by smrz10** [comment]
> THANK YOU!
> 
> I edited the node_helper.js file inline, then rebooted and it worked! I did have to make a slight change to your text above and ended up with (I did try formatting as code but couldn't force the new line on here):
> //const container = $(".entry--1qTEOKKt")[0];
> const container = $("._1qTEOKKt")[0];
> 
> Thank you so much - my wife is learning Spanish and this will make her day!

De nada ;-) (You're welcome)

**Comment by smrz10** [comment]
> > I did this changes (node_helper.js):
> > `//const container = $(".entry--1qTEOKKt")[0];`
> > ` container = $("._1qTEOKKt")[0];`
> > and it works
> > `
> 
> You should do a pull request

Yes, I'll try this week

**Comment by daniel-windsor** [comment]
Fixed.  Only took nearly a year :sweat_smile:
